image: kmindi/android-ci:platforms-25-26-27

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  # Define cache-folders withing the build-folder to make it available for GitLab CI caching
  # http://stackoverflow.com/a/36050711/2170109
  # https://developer.android.com/studio/build/build-cache.html
  - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

stages:
  - build
  - test

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/
  - .android/build-cache/

build:tagged:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assembleDebug
  artifacts:
    name: "SoPraApp_{$CI_BUILD_TAG}"
    paths:
    - app/build/outputs/apk/
  only:
    - tags

build:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assembleDebug
  artifacts:
    name: "SoPraApp_{$CI_BUILD_ID}"
    expire_in: 1 week
    paths:
    - app/build/outputs/apk/
  except:
    - tags

test:unit:
  stage: test
  tags:
    - docker
  script:
    - ./gradlew test jacocoTestReport
    - cat "app/build/reports/jacoco/jacocoTestReport/html/index.html"
  coverage: '/Total.+?([0-9]{1,3})\%/'
  cache:
    key: ${CI_PROJECT_ID}
    paths:
    - .gradle/
    - .android/build-cache/
    policy: pull
  artifacts:
    name: "tests-unit-${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
    expire_in: 1 week
    paths:
      - "**/build/reports/**"

test:instrumentation:25:
  stage: test
  tags:
    - docker
    - kvm
  script:
    - echo no | avdmanager -v create avd --force --name test --abi google_apis/x86 --package "system-images;android-25;google_apis;x86"
    # - export SHELL=/bin/bash && emulator -avd test -no-window -no-audio & #prepend shell for bitness (32/64 bit) detection
    - export SHELL=/bin/bash && echo "no" | emulator -avd test -noaudio -no-window -gpu off -verbose -qemu &
    - adb wait-for-device
    - android-wait-for-emulator
    - export TERM=${TERM:-dumb}
    - export ADB_INSTALL_TIMEOUT=4 # minutes (2 minutes by default)
    - assure_emulator_awake.sh "./gradlew connectedAndroidTest"
    - ./gradlew createDebugCoverageReport
    - cat "app/build/reports/coverage/debug/index.html"
  coverage: '/Total.+?([0-9]{1,3})\%/'
  artifacts:
    name: "tests-instrumentation-25-${CI_BUILD_NAME}"
    expire_in: 1 week
    paths:
      - "**/build/reports/**"

test:instrumentation:26:
  stage: test
  tags:
    - docker
    - kvm
  script:
    - echo no | avdmanager -v create avd --force --name test --abi google_apis/x86 --package "system-images;android-26;google_apis;x86"
    # - export SHELL=/bin/bash && emulator -avd test -no-window -no-audio & #prepend shell for bitness (32/64 bit) detection
    - export SHELL=/bin/bash && echo "no" | emulator -avd test -noaudio -no-window -gpu off -verbose -qemu &
    - adb wait-for-device
    - android-wait-for-emulator
    - export TERM=${TERM:-dumb}
    - export ADB_INSTALL_TIMEOUT=4 # minutes (2 minutes by default)
    - assure_emulator_awake.sh "./gradlew connectedAndroidTest"
    - ./gradlew createDebugCoverageReport
    - cat "app/build/reports/coverage/debug/index.html"
  coverage: '/Total.+?([0-9]{1,3})\%/'
  artifacts:
    name: "tests-instrumentation-26-${CI_BUILD_NAME}"
    expire_in: 1 week
    paths:
      - "**/build/reports/**"
