package de.uni_stuttgart.informatik.sopra.sopraapp.damagecases;

/**
 * DBManager Created by Alexander on 10.11.2017.
 * Description:
 **/
public class AuthorizationManager {

    private static AuthorizationManager INSTANCE;

    public static AuthorizationManager getINSTANCE() {
        if (INSTANCE == null)
            INSTANCE = new AuthorizationManager();
        return INSTANCE;
    }

    private AuthorizationManager() {
        //TODO: Autogenerated Singletone
    }

    public boolean isAuthorized(User user, Right right) {
        return false;
    }

    public void authorize(User user, Right right) {
    }
}
