package de.uni_stuttgart.informatik.sopra.sopraapp.damagecases;

/**
 * DBManager Created by Alexander on 10.11.2017.
 * Description:
 **/
public class AuthenticationManager {

    private static AuthenticationManager INSTANCE;

    public static AuthenticationManager getINSTANCE() {
        if (INSTANCE == null)
            INSTANCE = new AuthenticationManager();
        return INSTANCE;
    }

    private AuthenticationManager() {
        //TODO: Autogenerated Singletone
    }

    public boolean authenticate(String username, String password) {
        return false;
    }

    public boolean isAuthenticated(User user) {
        return false;
    }
}
