package de.uni_stuttgart.informatik.sopra.sopraapp.damagecases;

/**
 * DBManager Created by Alexander on 10.11.2017.
 * Description:
 **/
public class DBManager {

    private static DBManager INSTANCE;
    private static DatabaseConnection db;

    public static DBManager getINSTANCE() {
        if (INSTANCE == null)
            INSTANCE = new DBManager();
        return INSTANCE;
    }

    private DBManager() {
        //TODO: Autogenerated Singletone
    }
}
