package de.uni_stuttgart.informatik.sopra.sopraapp.damagecases;

/**
 * DBManager Created by Alexander on 10.11.2017.
 * Description:
 **/
public class StorageManager {

    private static StorageManager INSTANCE;

    public static StorageManager getINSTANCE() {
        if (INSTANCE == null)
            INSTANCE = new StorageManager();
        return INSTANCE;
    }

    private StorageManager() {
        //TODO: Autogenerated Singletone
    }
}
