package de.uni_stuttgart.informatik.sopra.sopraapp.damagecases;

/**
 * DBManager Created by Alexander on 10.11.2017.
 * Description:
 **/
public class UserManager {

    private static UserManager INSTANCE;

    public static UserManager getINSTANCE() {
        if (INSTANCE == null)
            INSTANCE = new UserManager();
        return INSTANCE;
    }

    private UserManager() {
        //TODO: Autogenerated Singletone
    }

    public boolean addUser(Data data) {
        return false;
    }
    public boolean deleteUser(User user) {
        return false;
    }

}
